import Navbar from './components/navbar/Navbar';
import Footer from './components/footer/Footer';
import './styles/globals.css';

export const metadata = {
  title: 'E-Commerce',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
